# Generated by Django 4.2.8 on 2024-03-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_review_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
